#!/bin/bash

set -e

echo "Creating required files and directories..."

mkdir -p var/{pids,run,log}
touch var/log/app.log
cat > config/database.yml <<- EOM
defaults: &defaults
  host: localhost
  encoding: utf8

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
EOM

echo "Installing dependencies..."

nix-shell -p bundix --run "bundix -l"

nix-shell shell.nix --pure --run '
npm install
psc-package install

echo "Setting up the database..."

rake db:setup

echo "Building the editor..."
gulp build:editor

echo "Building the reader..."
gulp build:reader

echo "Building the countdown page..."
gulp build:countdown

echo "Success!"
'
