#!/bin/bash

if [ "$1" = "--force-gems" ]; then
    force_gems=true
fi

updates=0

# only update ruby gems in Nix if Gemfile has changed
if ! git diff-index --quiet HEAD Gemfile || [ "$force_gems" = true ]; then
    gem_update="echo 'Updating gems...'; rm Gemfile.lock; bundle lock && bundix;"
    ((updates++))
fi

if [ $updates -gt 0 ]; then
    nix-shell utils.nix --run "$gem_update"
else
    echo "No changes to Gemfile. Nothing to update."
    echo ""
    echo "You can force an update with --force-gems."
fi
