#!/bin/bash

if [ "$1" = "--force-bower" ]; then
    force_bower=true
elif [ "$1" = "--force-gems" ]; then
    force_gems=true
elif [ "$1" = "--force-all" ]; then
    force_bower=true
    force_gems=true
fi

updates=0

# only update bower deps in Nix if there's been a change in bower.json
if ! git diff-index --quiet HEAD bower.json || [ "$force_bower" = true ]; then
    bower_update="echo 'Updating bower packages...'; bower2nix > bower-packages.nix;"
    ((updates++))
fi

# only update ruby gems in Nix if Gemfile has changed
if ! git diff-index --quiet HEAD Gemfile || [ "$force_gems" = true ]; then
    gem_update="echo 'Updating gems...'; rm Gemfile.lock; bundle lock && bundix;"
    ((updates++))
fi

if [ $updates -gt 0 ]; then
    nix-shell utils.nix --run "$bower_update $gem_update"
else
    echo "No changes to bower.json or Gemfile. Nothing to update."
    echo ""
    echo "You can force an update with --force-bower, --force-gems, or --force-all."
fi
